name: Release
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build release files
        id: build
        env:
          REFPOLY_VERSION: ${{ github.event.release.tag_name }}
        run: ./gradlew releaseInfo build
      - name: Publish release files
        uses: Kir-Antipov/mc-publish@4db8bd126f74d5e143822181a2b1201308e2c796
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

          curseforge-id: 943086
          curseforge-token: ${{ secrets.CURSEFORGE_API_KEY }}

          modrinth-id: HwPAr6Pu
          modrinth-token: ${{ secrets.MODRINTH_API_KEY }}

          version: ${{ steps.build.outputs.MOD_VERSION }}-${{ steps.build.outputs.MINECRAFT_VERSION }}
          game-versions: ${{ steps.build.outputs.MINECRAFT_VERSION }}
          dependencies: |
            refinedstorage(required){curseforge:243076}{modrinth:KDvYkUg3}
            polymorph(required){curseforge:388800}{modrinth:tagwiZkJ}
            refinedstorageaddons(optional){curseforge:272302}{modrinth:Z4Z5ccuT}
            rebornstorage(optional){curseforge:256662}
            universalgrid(optional){curseforge:536160}
